src/Entity/Car.php
<?php

namespace App\Entity;

use App\Repository\CarRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CarRepository::class)]
class Car
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $price = null;

    #[ORM\Column(length: 255)]
    private ?string $year = null;

    #[ORM\Column(length: 255)]
    private ?string $kilometer = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $caracteristics = null;

    #[ORM\Column(length: 255)]
    private ?string $energy = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\ManyToOne(inversedBy: 'car')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\OneToOne(mappedBy: 'car', targetEntity: CarImage::class, cascade: ['persist', 'remove'])]
    private ?CarImage $carImage = null;

    public function __construct()
    {
        // Mettez à jour le constructeur pour ne pas initialiser la collection ici
        // $this->carImage = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getYear(): ?string
    {
        return $this->year;
    }

    public function setYear(string $year): static
    {
        $this->year = $year;

        return $this;
    }

    public function getKilometer(): ?string
    {
        return $this->kilometer;
    }

    public function setKilometer(string $kilometer): static
    {
        $this->kilometer = $kilometer;

        return $this;
    }

    public function getCaracteristics(): ?string
    {
        return $this->caracteristics;
    }

    public function setCaracteristics(string $caracteristics): static
    {
        $this->caracteristics = $caracteristics;

        return $this;
    }

    public function getEnergy(): ?string
    {
        return $this->energy;
    }

    public function setEnergy(string $energy): static
    {
        $this->energy = $energy;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return CarImage|null
     */
    public function getCarImage(): ?CarImage
    {
        return $this->carImage;
    }

    public function setCarImage(?CarImage $carImage): static
    {
        $this->carImage = $carImage;

        // Assurez-vous de mettre à jour le côté inverse de la relation dans CarImage
        if ($carImage !== null && $carImage->getCar() !== $this) {
            $carImage->setCar($this);
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Car::class)]
    private Collection $car;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Service::class)]
    private Collection $service;

    #[ORM\ManyToMany(targetEntity: Testimonial::class, inversedBy: 'users')]
    private Collection $testimonial;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: OpeningDay::class)]
    private Collection $openingDay;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Adresse $adresse = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Contact::class)]
    private Collection $contact;

    public function __construct()
    {
        $this->car = new ArrayCollection();
        $this->service = new ArrayCollection();
        $this->testimonial = new ArrayCollection();
        $this->openingDay = new ArrayCollection();
        $this->contact = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    /**
     * @return Collection<int, Car>
     */
    public function getCar(): Collection
    {
        return $this->car;
    }

    public function addCar(Car $car): static
    {
        if (!$this->car->contains($car)) {
            $this->car->add($car);
            $car->setUser($this);
        }

        return $this;
    }

    public function removeCar(Car $car): static
    {
        if ($this->car->removeElement($car)) {
            // set the owning side to null (unless already changed)
            if ($car->getUser() === $this) {
                $car->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Service>
     */
    public function getService(): Collection
    {
        return $this->service;
    }

    public function addService(Service $service): static
    {
        if (!$this->service->contains($service)) {
            $this->service->add($service);
            $service->setUser($this);
        }

        return $this;
    }

    public function removeService(Service $service): static
    {
        if ($this->service->removeElement($service)) {
            // set the owning side to null (unless already changed)
            if ($service->getUser() === $this) {
                $service->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Testimonial>
     */
    public function getTestimonial(): Collection
    {
        return $this->testimonial;
    }

    public function addTestimonial(Testimonial $testimonial): static
    {
        if (!$this->testimonial->contains($testimonial)) {
            $this->testimonial->add($testimonial);
        }

        return $this;
    }

    public function removeTestimonial(Testimonial $testimonial): static
    {
        $this->testimonial->removeElement($testimonial);

        return $this;
    }

    /**
     * @return Collection<int, OpeningDay>
     */
    public function getOpeningDay(): Collection
    {
        return $this->openingDay;
    }

    public function addOpeningDay(OpeningDay $openingDay): static
    {
        if (!$this->openingDay->contains($openingDay)) {
            $this->openingDay->add($openingDay);
            $openingDay->setUser($this);
        }

        return $this;
    }

    public function removeOpeningDay(OpeningDay $openingDay): static
    {
        if ($this->openingDay->removeElement($openingDay)) {
            // set the owning side to null (unless already changed)
            if ($openingDay->getUser() === $this) {
                $openingDay->setUser(null);
            }
        }

        return $this;
    }

    public function getAdresse(): ?Adresse
    {
        return $this->adresse;
    }

    public function setAdresse(?Adresse $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    /**
     * @return Collection<int, Contact>
     */
    public function getContact(): Collection
    {
        return $this->contact;
    }

    public function addContact(Contact $contact): static
    {
        if (!$this->contact->contains($contact)) {
            $this->contact->add($contact);
            $contact->setUser($this);
        }

        return $this;
    }

    public function removeContact(Contact $contact): static
    {
        if ($this->contact->removeElement($contact)) {
            // set the owning side to null (unless already changed)
            if ($contact->getUser() === $this) {
                $contact->setUser(null);
            }
        }

        return $this;
    }
    public function __toString(): string
    {
        return $this->email . "(" . $this->id .  ")";
    }

}

src/Controller/CarController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Form\CarContactType;
use App\Form\ContactType;
use App\Repository\CarRepository;
use App\Repository\OpeningDayRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Mailer\MailerInterface;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Mime\Email;

class CarController extends AbstractController
{
    #[Route('/car/{slug}', name: 'car_detail')]
public function carDetail(string $slug, CarRepository $carRepository, OpeningDayRepository $openingDayRepository, Request $request, MailerInterface $mailer, SessionInterface $session, EntityManagerInterface $entityManager): Response
{
    // Récupérer la voiture par le slug depuis le repository
    $car = $carRepository->findOneBy(['slug' => $slug]);
    $openingDays = $openingDayRepository->findAll();

    // Vérifier si la voiture existe
    if (!$car) {
        throw $this->createNotFoundException('Car not found');
    }


    $form = $this->createForm(CarContactType::class, null, [
        'car_name' => $car->getName(),
        'car_price' => $car->getPrice(),
        'car_id' => $car->getId(),
    ]);

    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        $data = $form->getData();

        // Save to the database
        $contact = new Contact();
        $contact->setFirstName($data->getFirstName());
        $contact->setLastName($data->getLastName());
        $contact->setEmail($data->getEmail());
        $contact->setPhoneNumber($data->getPhoneNumber());
        $contact->setContent($data->getContent());
        $contact->setCarId($car->getId());
        $contact->setCarName($car->getName());
        $contact->setCarPrice($car->getPrice());

        $entityManager->persist($contact);
        $entityManager->flush();

        // Send email
        $address = $data->getEmail();
        $content = $data->getContent();
        $subject = $car->getName() . "/" . $car->getPrice();

        $email = (new Email())
            ->from($address)
            ->to('zaki.tehami@gmail.com')
            ->subject($subject)
            ->text($content);

        $mailer->send($email);

        $session->getFlashBag()->add('success', 'Votre message a été envoyé avec succès.');
    }





    // Passer la voiture à la vue
    return $this->render('car/carDetail.html.twig', [
        'car' => $car,
        'openingDays' => $openingDays,
        'formulaire' => $form->createView(),
    ]);
}
    #[Route('/car', name: 'car_list')]
    public function carList(OpeningDayRepository $openingDayRepository): Response
    {
        $openingDays = $openingDayRepository->findAll();
        // Ajoutez ici la logique pour récupérer la liste des voitures

        return $this->render('car/carDetail.html.twig', [
            'openingDays' => $openingDays,
        ]);
    }

    #[Route('/cars', name: 'cars_list')]
public function carsList(CarRepository $carRepository, OpeningDayRepository $openingDayRepository): Response
{
    // Récupérer la liste des voitures depuis le repository
    $cars = $carRepository->findAll();
    $openingDays = $openingDayRepository->findAll();

    // Passer la liste des voitures à la vue
    return $this->render('car/cars_list.html.twig', [
        'cars' => $cars,
        'openingDays' => $openingDays,
    ]);
}

#[Route('/cars/filtered', name: 'filtered_cars_list')]
public function filteredCarsList(Request $request, CarRepository $carRepository, OpeningDayRepository $openingDayRepository): Response
{
    $filters = $request->request->all();

    // Add your filtering logic using $filters
    $filteredCars = $carRepository->findByFilters($filters);
    $openingDays = $openingDayRepository->findAll();

    // Render the filtered car list
    return $this->render('car/filtered_cars_list.html.twig', [
        'cars' => $filteredCars,
        'openingDays' => $openingDays,
    ]);
}

}

templates/car/carDetail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails de {{ car.name }}{% endblock %}

{% block body %}
    <div class="px-4 pt-5 my-5 text-center border-bottom">
        <h1 class="display-4 fw-bold text-body-emphasis">{{ car.name|striptags }}</h1>
        <div class="col-lg-6 mx-auto">
            <p class="lead mb-4">{{ car.caracteristics|striptags }}</p>
        </div>
        <div class="overflow-hidden">
            <div class="container px-5">
                {% if car.carImage %}
            {% set firstCarImage = car.carImage %}
            <img src="{{ asset('uploads/' ~ firstCarImage.filename) }}" class="card-img-top" alt="Image">
        {% endif %}
            </div>
        </div>
    </div>

    	<div class="container col-xxl-8 px-4 py-5">
		<div class="row flex-lg-row-reverse align-items-center g-5 py-5">
			<div
				class="col-10 col-sm-8 col-lg-6 contact">
				{# Afficher les éventuels messages flash #}
				{% for flash_message in app.flashes('success') %}
					<div class="alert alert-success">{{ flash_message }}</div>
				{% endfor %}

			</div>
			<div class="col-lg-6">
				<h1 class="display-5 fw-bold text-body-emphasis lh-1 mb-5">Vous êtes intéressé par cette voiture ? Contacter nous!</h1>

				{# Afficher le formulaire #}
				{{ form_start(formulaire, {'attr': {'class': 'needs-validation'}}) }}
				<form class="needs-validation" novalidate="">
					<form class="needs-validation" novalidate="">
						<div class="row g-3">
							<div class="col-sm-6 mb-3">
								{{ form_row(formulaire.firstName, {'label': false,'attr': {'class': 'form-control', 'placeholder': 'Votre Prénom', 'required': 'required'}}) }}
								{{ form_errors(formulaire.firstName) }}
							</div>
							<div class="col-sm-6 mb-3">
								{{ form_row(formulaire.lastName, {'label': false,'attr': {'class': 'form-control', 'placeholder': 'Votre Nom', 'required': 'required'}}) }}
								{{ form_errors(formulaire.lastName) }}
							</div>
						</div>

						{# Champ Email #}
						<div class="col-12 mb-3">
							{{ form_row(formulaire.email, {'label': false, 'attr': {'class': 'form-control', 'placeholder': 'Votre email', 'required': 'required'}}) }}
							{{ form_errors(formulaire.email) }}
						</div>

						{# Champ Numéro de téléphone #}
						<div class="col-12 mb-3">
							{{ form_row(formulaire.phoneNumber, {'label': false, 'attr': {'class': 'form-control', 'placeholder': 'Votre numéro de téléphone'}}) }}
							{{ form_errors(formulaire.phoneNumber) }}
						</div>

						{# Champ Message avec une hauteur de 100px #}
						<div class="col-12 mb-3">
							{{ form_row(formulaire.content, {'label': false, 'attr': {'class': 'form-control', 'placeholder': 'Votre message', 'style': 'height: 100px;', 'required': 'required'}}) }}
							{{ form_errors(formulaire.content) }}
						</div>

						<hr class="my-4">
						{{ form_end(formulaire) }}
					</form>
				</div>
			</div>
		</div>
{% endblock %}

templates/car/car_card.html.twig
<div class="col-lg">
    <div class="card mb-4 rounded-3 shadow-sm" style="width: 100%;">
        {% if car.carImage %}
            {% set firstCarImage = car.carImage %}
            <img src="{{ asset('uploads/' ~ firstCarImage.filename) }}" class="card-img-top img-fluid" alt="Image" style="height: 300px; object-fit: cover;">
        {% endif %}
        <div class="card-body">
            <h1 class="card-title">{{ car.name }}</h1>
            <ul class="list-unstyled mt-3 mb-4">
                <li>{{ car.year }}</li>
                <li>{{ car.kilometer }} KM</li>
                <li>{{ car.energy }}</li>
            </ul>
            <a href="{{ path('car_detail', {'slug': car.slug}) }}" class="nav-link text-white">
                <button type="button" class="w-100 btn btn-dark btn-lg btn-outline">Voir le détail</button>
            </a>
        </div>
        <div class="card-header py-3">
            <h3 class="card-title pricing-card-title">{{ car.price }}<small class="text-body-secondary fw-light">€</small>
            </h3>
        </div>
    </div>
</div>

templates/car/cars_list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos véhicules d'occasion{% endblock %}

{% block body %}
    <div class="container text-center">
        <h1 class="display-5 fw-bold text-body-emphasis mt-5 mb-5">Nos véhicules d'occasion</h1>

        <!-- Filters -->
        <div class="mb-5 d-flex align-items-center">
            <select id="fuel" class="form-select me-3">
                <option value="">Carburant:</option>
                <option value="essence">Essence</option>
                <option value="diesel">Diesel</option>
            </select>

            <select id="price" class="form-select me-3">
                <option value="">Prix:</option>
                <option value="0-5000">0 - 5000 €</option>
                <option value="5100-10000">5100 € - 1 0000 €</option>
                <option value="11000-15000">11000 € - 15000 €</option>
                <option value="16000-20000">16000 € - 20000 €</option>
                <option value="21000-25000">21000 € - 25000 €</option>
                <option value="26000-30000">26000 € - 30000 €</option>
                <option value="31000-40000">31000 € - 40000 €</option>
                <option value="41000-50000">41000 € - 50000 €</option>
                <option value="51000-60000">51000 € - 60000 €</option>
                <option value="61000-70000">61000 € - 70000 €</option>
            </select>

            <select id="kilometer" class="form-select me-3">
            <option value="">Kilométrage:</option>
                <option value="0-25000">0 - 25000 km</option>
                <option value="26000-50000">26000 km - 50000 km</option>
                <option value="51000-75000">51000 km - 75000 km</option>
                <option value="76000-100000">76000 km - 100000 km</option>
                <option value="101000-125000">101000 km - 125000 km</option>
                <option value="126000-150000">126000 km - 150000km</option>
            </select>

            <select id="year" class="form-select me-3">
                <option value="">Année:</option>
                <option value="2010-2015">2010 - 2015</option>
                <option value="2016-2020">2016 - 2020</option>
                <option value="2021-2025">2021 - 2025</option>
            </select>

            <button id="applyFilters" class="btn btn-dark btn-sm btn-outline">Appliquer</button>
        </div>
    </div>
        <!-- Car list container -->
<div id="carListContainer" class="container">

	{% for car in cars %}
		{% if loop.index0 % 3 == 0 %}
			{% if loop.index0 != 0 %}
			</div>
		{% endif %}
		<div class="row">
		{% endif %}


		{% include 'car/car_card.html.twig' with {'car': car} %}


		{% if loop.last %}
		</div>
	{% endif %}
{% endfor %}


    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
    $(document).ready(function() {
        // Function to update car list based on filters
        function updateCarList() {
            var filters = {
                fuel: $('#fuel').val(),
                price: $('#price').val(),
                kilometer: $('#kilometer').val(),
                year: $('#year').val()
            };

            $.ajax({
                url: "{{ path('filtered_cars_list') }}", // Mise à jour avec le nom de votre route pour la liste de voitures filtrées
                method: 'POST',
                data: filters,
                success: function(response) {
                    $('#carListContainer').html(response);
                },
                error: function(error) {
                    console.error('Erreur lors de la récupération de la liste de voitures filtrées :', error);
                }
            });
        }

        // Event listener for apply button click
        $('#applyFilters').click(function() {
            updateCarList();
        });
    });
</script>
{% endblock %}

templates/car/filtered_cars_list.html.twig
<div id="carListContainer" class="container">
    {% for car in cars %}
        {% if loop.index0 % 3 == 0 %}
            {% if loop.index0 != 0 %}
                </div>
            {% endif %}
            <div class="row">
        {% endif %}

        {% include 'car/car_card.html.twig' with {'car': car} %}

        {% if loop.last %}
            {% set remainingCars = 3 - loop.index % 3 %}
            {% if remainingCars > 0 and remainingCars < 3 %}
                {% for i in 1..remainingCars %}
                    <div class="col-lg">
                        <!-- Ajoutez un contenu vide ou un espace réservé pour les voitures manquantes -->
                    </div>
                {% endfor %}
            {% endif %}
            </div>
        {% endif %}
    {% endfor %}
</div>